version: 0.0
os: linux
files:
  - source: /src
    destination: /home/ubuntu/recipeUniverse/backend

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
  ValidateService:
    - location: scripts/validate.sh
      timeout: 300
