server:
  port: 8080
  servlet:
    context-path: /api/ur
    encoding:
      charset: UTF-8
      enabled:
        force: true

spring:
  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      s3:
        bucket: ${S3_BUCKET_NAME}
      region:
        static: ap-northeast-2
  datasource:
    url: jdbc:mariadb://localhost:3306/dev
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

opensearch:
  username: ${OPENSEARCH_USERNAME}
  password: ${OPENSEARCH_PASSWORD}
  host : ${OPENSEARCH_HOST}
  port : ${OPENSEARCH_PORT}
