server:
  port: 8080
  servlet:
    context-path: /api/ur
    encoding:
      charset: UTF-8
      enabled:
        force: true

spring:
  datasource:
    url: jdbc:mariadb://sideproject.cdymswa8ehy1.ap-northeast-2.rds.amazonaws.com/recipeUniverseDB
    driver-class-name: org.mariadb.jdbc.Driver
    username: recipeUniverse
    password: kmu2018

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      #none, update, create
      ddl-auto: none

  ai:
    openai:
      model: gpt-3.5-turbo
      api-key: ${OPENAI_API_KEY}

  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      s3:
        bucket: ${S3_BUCKET_NAME}
      region:
        static: ap-northeast-

opensearch:
  username: ${OPENSEARCH_USERNAME}
  password: ${OPENSEARCH_PASSWORD}
  host : ${OPENSEARCH_HOST}
  port : ${OPENSEARCH_PORT}
