server:
  port: 8080
  servlet:
    context-path: /api/ur
    encoding:
      charset: UTF-8
      enabled:
        force: true

spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PWD}

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      #none, update, create
      ddl-auto: none

  ai:
    openai:
      model: gpt-3.5-turbo
      api-key: ${OPENAI_API_KEY}

  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      s3:
        bucket: ${S3_BUCKET_NAME}

  security:
    oauth2:
      client:
        registration:
          google:
            authorization-grant-type: authorization_code
            client-id: ${OAUTH2_GOOGLE_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT}
            client-name: ${OAUTH2_GOOGLE_NAME}
            client-authentication-method: client_secret_basic
            scope: openid,email
  redis:
    host: localhost
    port: 6379

  opensearch:
    host: ${OPENSEARCH_HOST}

  springdoc:
    api-docs:
      path: /docs
    swagger-ui:
      path: /docs/ui

jwt:
  secret: 0ed89e38998c31d591261887d37e2148c8dea714330af0febac9b9d22e62517c


