  push:
    branches:
      - backend-main  # backend-main 브랜치에 푸시될 때 실행

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 현재 리포지토리의 코드를 체크아웃

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4  # SSH 에이전트를 설정하여 EC2에 접속할 수 있도록 함
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}  # GitHub Secrets에 저장된 SSH 프라이빗 키 사용

    - name: Copy project files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r * ${{ secrets.USER }}@${{ secrets.HOST }}:/RecipeUniverse/backend/
