on:
  push:
    branches:
      - backend-main  # backend-main 브랜치에 푸시될 때 실행

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 현재 리포지토리의 코드를 체크아웃
    

     # Step 1: EC2에 접근하기 위한 SSH 설정
    - name: Set up SSH for EC2 Access
      uses: webfactory/ssh-agent@v0.5.4  # SSH 에이전트를 설정하여 EC2에 접속할 수 있도록 함
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # GitHub Secrets에 저장된 EC2 접근용 프라이빗 키 사용

    # Step 2: EC2에 프로젝트 파일을 전송
    - name: Copy project files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -P 22 -r ./* ${{ secrets.USER }}@${{ secrets.HOST }}:/home/ubuntu/recipeUniverse/backend

    - name: Deploy and Run Docker on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
        cd /home/ubuntu/recipeUniverse/backend/
        # .env 파일이 필요할 경우 복사하거나 생성하는 명령어를 여기에 추가 가능
        # Docker를 사용하여 컨테이너 빌드 및 실행
        sudo docker-compose down  # 기존 컨테이너 중지 및 삭제
        sudo docker-compose up -d --build  # 새로 빌드하여 백그라운드에서 실행
        EOF
