name: Frontend Deployment

on:
  push:
    branches:
      - frontend-main  # main 브랜치에 푸시될 때 실행

jobs:
  deploy-frontend:
    runs-on: 
      - self-hosted
      - Linux

    steps:
      # Step 3: 프로젝트 의존성 설치 및 빌드
      - name: Install dependencies and build
        run: |
          pwd
          ls -al
          whoami